---
title: "QA3D Report"
output: pdf_document
params:
  iterations: NULL
  subsample: NULL
  pcalign: NULL
  kmeans: NULL
  procedure: NULL
  vara: NULL
  vara2: NULL
  report_pw: NULL
  report_gr: NULL
  date: NULL
  scannerid: NULL
  analyst: NULL
  breake: NULL
  breakk: NULL
  x: NULL
  y: NULL
  z: NULL
  d: NULL
  attributes: NULL
  choose: NULL
---
QA3D Version: `r packageVersion("QA3D")`

Date: `r params$date`

`r if(params$attributes != "") {paste("Attributes:", params$attributes, sep=" ")}`

`r if(params$scannerid != "") {paste("Scanner ID:", params$scannerid, sep=" ")}`

`r if(params$analyst != "") {paste("Analyst:", params$analyst, sep=" ")}`

### Registration Parameters
ICP Iterations: `r params$iterations`

ICP subsample: `r params$subsample`

`r if(params$subsample) {paste("Subsample %:", params$vara2, sep=" ")}`

PC Align: `r params$pcalign`

Early Break: `r params$breake`

`r if(params$pcalign && params$breake) {paste("Break Point:", params$breakk, sep=" ")}`

K-means simplify: `r params$kmeans`

`r if(params$kmeans) {paste("K-means %:", params$vara, sep=" ")}`

Procedure: `r params$procedure`

`r if(params$procedure == "Custom") {paste("X:", params$x, sep=" ")}`

`r if(params$procedure == "Custom") {paste("Y:", params$y, sep=" ")}`

`r if(params$procedure == "Custom") {paste("Z:", params$z, sep=" ")}`

`r if(params$procedure == "Custom") {paste("Density:", params$d, sep=" ")}`

`r if(params$procedure == "Choose") {paste("Target:", params$choose, sep=" ")}`

### Grand Results
`r kable(params$report_gr)`


### Pairwise Results
`r kable(params$report_pw)`